name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Construire l'image Docker pour le frontend
      - name: Build frontend Docker image
        run: docker build -f Frontend/Dockerfile -t frontend-image .
